In [1]:
people = {
    "first": ['Corey', 'Jane', 'John'],
    "last": ['Schafer', 'Doe', 'Doe'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

import pandas as pd

df = pd.DataFrame(people)

df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [4]:
df['full_name'] = df['first'] + ' ' + df['last']

In [5]:
df

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [11]:
df.drop(columns =['full_name'], inplace = True)

In [12]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [13]:
df['full_name'] = df['first'] + ' ' + df['last']

In [14]:
df.drop(columns =['first','last'], inplace = True)

In [15]:
df

                     email      full_name
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [17]:
df['full_name'].str.split(' ',expand = True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [18]:
df[['first','last']] = df['full_name'].str.split(' ',expand = True)

In [19]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

In [23]:
new_row = pd.DataFrame([{'first': 'Tony'}])

df = pd.concat([df, new_row], ignore_index=True)

In [24]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

In [25]:
people = {
    'first': ['Tony', 'Steve'],
    'last': ['Stark', 'Rogers'],
    'email': ['IronMan@avenge.com', 'Cap@avenge.com']
}

df2 = pd.DataFrame(people)

In [26]:
df2

   first    last               email
0   Tony   Stark  IronMan@avenge.com
1  Steve  Rogers      Cap@avenge.com

In [28]:
pd.concat([df, df2], ignore_index=True, sort=False)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark
5           Cap@avenge.com            NaN  Steve   Rogers

In [29]:
df = pd.concat([df, df2], ignore_index=True, sort=False)

In [30]:
df

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark
5           Cap@avenge.com            NaN  Steve   Rogers

In [31]:
df.drop(index = 5)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark

In [33]:
df.drop(index = df[df['last'] == 'Doe'].index)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark
5           Cap@avenge.com            NaN  Steve   Rogers

In [35]:
filt = df['last'] == 'Doe'
df.drop(index = df[filt].index)

                     email      full_name  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark
5           Cap@avenge.com            NaN  Steve   Rogers