In [2]:
people = {
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Doe"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@email.com", "JohnDoe@email.com"]
}

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(people)

In [5]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [7]:
filt = (df['last'] == 'Schafer')

In [8]:
df[filt]

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com

In [20]:
df.loc[filt, 'email']

0    CoreyMSchafer@gmail.com
Name: email, dtype: str

In [22]:
file = (df['last'] == 'Doe') & (df['first'] == 'John')

In [23]:
df[file]

  first last              email
2  John  Doe  JohnDoe@email.com

In [25]:
df.loc[~file, 'email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: str