In [1]:
people = {
    "first": ['Corey', 'Jane', 'John', 'Adam'],
    "last": ['Schafer', 'Doe', 'Doe', 'Doe'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', 'AdamDoe@gmail.com']
}

import pandas as pd

df = pd.DataFrame(people)

df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe        AdamDoe@gmail.com

In [2]:
df.sort_values(by='last')

   first     last                    email
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe        AdamDoe@gmail.com
0  Corey  Schafer  CoreyMSchafer@gmail.com

In [3]:
df.sort_values(by='last', ascending = False)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe        AdamDoe@gmail.com

In [4]:
df.sort_values(by=['last', 'first'], ascending = False) #last first and first it last equal

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
2   John      Doe        JohnDoe@email.com
1   Jane      Doe        JaneDoe@email.com
3   Adam      Doe        AdamDoe@gmail.com

In [6]:
df.sort_values(by=['last', 'first'], ascending = [False,True], inplace = True) #corresponds to columns in 'by'

In [7]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
3   Adam      Doe        AdamDoe@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [9]:
df.sort_index()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe        AdamDoe@gmail.com

In [10]:
df.sort_index()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe        AdamDoe@gmail.com

In [11]:
df['first'].sort_values()

3     Adam
0    Corey
1     Jane
2     John
Name: first, dtype: str