In [1]:
people = {
    "first": ['Corey', 'Jane', 'John'],
    "last": ['Schafer', 'Doe', 'Doe'],
    "email": ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

import pandas as pd

df = pd.DataFrame(people)

df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [2]:
df.columns = ['f_n','l_n','mail']

In [3]:
df

     f_n      l_n                     mail
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [5]:
df.columns = [x.upper() for x in df.columns]

In [6]:
df

     F_N      L_N                     MAIL
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [7]:
df.columns = df.columns.str.replace(' ','_')

In [9]:
df.rename(columns = {'F_N':'f_n'}, inplace = True)

In [10]:
df

     f_n      L_N                     MAIL
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [11]:
df.loc[2] = ['John', 'Smith' , 'JohnSmith@gmail.com']

In [12]:
df

     f_n      L_N                     MAIL
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith      JohnSmith@gmail.com

In [15]:
df.loc[2, ['f_n']] = ['Jack']

In [16]:
df

     f_n      L_N                     MAIL first
0  Corey  Schafer  CoreyMSchafer@gmail.com   NaN
1   Jane      Doe        JaneDoe@email.com   NaN
2   Jack    Smith      JohnSmith@gmail.com  Jack

In [19]:
df.at[2, 'f_n'] = 'James'

In [20]:
df

     f_n      L_N                     MAIL first
0  Corey  Schafer  CoreyMSchafer@gmail.com   NaN
1   Jane      Doe        JaneDoe@email.com   NaN
2  James    Smith      JohnSmith@gmail.com  Jack

In [25]:
filt = (df['MAIL'] == 'JaneDoe@email.com')
df[filt]

    f_n  L_N               MAIL first
1  Jane  Doe  JaneDoe@email.com   NaN

In [26]:
filt = (df['MAIL'] == 'JaneDoe@email.com')
df.loc[filt, 'L_N'] = 'Doeee'

In [27]:
df

     f_n      L_N                     MAIL first
0  Corey  Schafer  CoreyMSchafer@gmail.com   NaN
1   Jane    Doeee        JaneDoe@email.com   NaN
2  James    Smith      JohnSmith@gmail.com  Jack

In [30]:
df['MAIL'] = df['MAIL'].str.lower()

In [31]:
df

     f_n      L_N                     MAIL first
0  Corey  Schafer  coreymschafer@gmail.com   NaN
1   Jane    Doeee        janedoe@email.com   NaN
2  James    Smith      johnsmith@gmail.com  Jack

In [32]:
df['MAIL'].apply(len)

0    23
1    17
2    19
Name: MAIL, dtype: int64

In [33]:
def return_email(MAIL):
    return MAIL.upper()

In [37]:
df['MAIL'].apply(return_email)

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@EMAIL.COM
2        JOHNSMITH@GMAIL.COM
Name: MAIL, dtype: str

In [38]:
df['MAIL'] = df['MAIL'].apply(return_email)

In [39]:
df

     f_n      L_N                     MAIL first
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM   NaN
1   Jane    Doeee        JANEDOE@EMAIL.COM   NaN
2  James    Smith      JOHNSMITH@GMAIL.COM  Jack

In [40]:
df['MAIL'] = df['MAIL'].apply(lambda x: x.lower())  #apply on specific series

In [41]:
df

     f_n      L_N                     MAIL first
0  Corey  Schafer  coreymschafer@gmail.com   NaN
1   Jane    Doeee        janedoe@email.com   NaN
2  James    Smith      johnsmith@gmail.com  Jack

In [42]:
df.apply(len) #not what we want

f_n      3
L_N      3
MAIL     3
first    3
dtype: int64

In [43]:
df.apply(len, axis = 'columns') #apply on whole df

0    4
1    4
2    4
dtype: int64

In [44]:
df.apply(pd.Series.min) #as strings, aplhabetic order

f_n                        Corey
L_N                        Doeee
MAIL     coreymschafer@gmail.com
first                       Jack
dtype: str

In [45]:
df.apply(lambda x: x.min())

f_n                        Corey
L_N                        Doeee
MAIL     coreymschafer@gmail.com
first                       Jack
dtype: str

In [ ]:
#applymap (deprecated to map) for individual data in df (not series)

In [50]:
# df.map(len) - needed float values

In [52]:
df.head()
df.dtypes

f_n      str
L_N      str
MAIL     str
first    str
dtype: object

In [53]:
df.drop('first', axis=1, inplace=True)

In [54]:
df.map(str.lower)

     f_n      L_N                     MAIL
0  corey  schafer  coreymschafer@gmail.com
1   jane    doeee        janedoe@email.com
2  james    smith      johnsmith@gmail.com

In [58]:
df['L_N'].map({'schafer': 'Shafir','doeee': 'Dovee'})

0    NaN
1    NaN
2    NaN
Name: L_N, dtype: str

In [59]:
#if we do not give any name in above map , then NaN (fixed by replace)

In [60]:
df['L_N'].replace({'schafer': 'Shafir','doeee': 'Dovee'})

0    Schafer
1      Doeee
2      Smith
Name: L_N, dtype: str

In [61]:
df['L_N'] = df['L_N'].replace({'schafer': 'Shafir','doeee': 'Dovee'})

In [62]:
df

     f_n      L_N                     MAIL
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane    Doeee        janedoe@email.com
2  James    Smith      johnsmith@gmail.com